### ISSUE TITLE
failing installation

### ISSUE THREAD

**Issue by arnounesco** [iodepo/oih-ui-docker#28]
Still unable to install this release branch following the instruction in the README!

**Comment by dev-marcoC** [comment]
Hi Arno,

@petrocel  and I have thoroughly reviewed the issue, and we ultimately concluded that it was related to certificate generation. The Let's Encrypt container returned an error indicating that it couldn't create new certificates because too many had been generated recently. After waiting for the retry period, we performed a completely clean installation, and it worked on the first try.

Anyway to simplify the process, we added a .sh script to the repository. You just need to download it from the repository, modify the path where it retrieves the Solr data, and run it to automatically set up the entire development environment without having to manually execute all the commands.

**Comment by arnounesco** [comment]
Marco,

checked this again, removed all dockers and all installation dirs
copied the setup_prod.sh to /data
made it executable
ran the script (with the default values from the script, which should be ok for now)

result : 

<img width="492" alt="Screenshot 2024-09-02 at 15 14 50" src="https://github.com/user-attachments/assets/d69dd893-b172-4f44-8662-877e1d91c70e">

**Comment by dev-marcoC** [comment]
Hi Arno,

@petrocel and I have rechecked the situation, and as you can see from this site:
https://tools.letsdebug.net/cert-search?m=domain&q=api.devsearch.oceaninfohub.org&d=168

![image](https://github.com/user-attachments/assets/6569afe1-ce05-486e-abbb-5bc5a9f36bdb)

The certificate for the frontend was generated successfully because there was an available slot. However, the certificate for the API wasn't generated due to all slots being filled, which is why the site returns a "failed to fetch" error.

![image](https://github.com/user-attachments/assets/84f056ca-eaa4-407b-8991-175229a8a222)


This happens because Let's Encrypt attempts to generate a new certificate for both the dev and API environments each time a clean installation is performed. While the installation process itself works, there's an issue with HTTPS caused by the limitations of Let's Encrypt certificates, which are free and therefore have certain constraints. These constraints lead to the available slots being quickly filled, causing the error.

Using paid certificates would obviously prevent this issue. In any case, Ale and I will do another clean installation tomorrow morning (when another slot for the API becomes available) to ensure everything works fine. After that, we'll update you on when you can try a fresh installation yourself.

**Comment by arnounesco** [comment]
Marco,

changed the installation and used devsearch.odis.org instead of devsearch.oceaninfohub.org

there is a certificate now, but the problem is still the same, still get the same error screen

**Comment by dev-marcoC** [comment]
Thank you, Arno, for changing the DNS. We will work on understanding what the problem is as soon as possible.

**Comment by arnounesco** [comment]
installation using the script works fine
